apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout-demo
  namespace: rollout-demo
spec:
  rules:
    - host: rollout-demo.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollout-demo
                port:
                  number: 80
